apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: journalingapp
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/JournalingAppKiii"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: journalingapp
type: Opaque
data:
  POSTGRES_DB: Sm91cm5hbGluZ0FwcEtpaWk=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: Zmlua2kxMjM=
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: Zmlua2kxMjM=
